const widgetsIds = {
  app: "app",
  filmsTableId: "films-table",
  filmsFormId: "films-form",
  adminTable: "adminTable",
  adminForm: "adminForm",
  profileButtonId: "profile-button",
  windowId: "mywindow",
  toolbarId: "myToolbar",
  usersInputId: "users-input",
  usersListId: "users-list",
  dashboard: "Dashboard",
  users: "Users",
  products: "Products",
  admin: "Admin",
  products_id: "id",
  products_title: "title",
  products_price: "price",
  tabuttons_id: "selector",
  tabbuttons_all: "All",
  tabbuttons_old: "Old",
  tabbuttons_modern: "Modern",
  tabbuttons_new: "New",
  filmTables_rank: "rank",
  filmTables_title: "title",
  filmTables_category: "categoryId",
  filmTables_votes: "votes",
  filmTables_rating: "rating",
  filmTables_year: "year",
  chart: "my-chart",
  admin_category: "value"
};

export default widgetsIds;
